# Generated by Django 4.2.7 on 2025-08-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.tag', verbose_name='Tags'),
        ),
    ]
